version: '3'

services:
  spark:
    build: 
      context: .
      dockerfile: ./Dockerfile    
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark
      - SPARK_WORKLOAD=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      # - '8888:8888'   
      # - '4040:4040'   
    volumes:
      - "./:/opt/spark:rw"  
   
  spark-worker:
    image: bitnami/spark:3.3.4
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8081:8081'
    volumes:
      - "./:/opt/spark:rw" 