services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
      - "./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
    ports:
      - "5433:5432"
    networks:
      - pg-networks
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -d nytaxi_db -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      pgdatabase:
        condition: service_healthy
    networks:
      - pg-networks

networks:
  pg-networks:
volumes:
  ny_taxi_postgres_data:
    